---
title: "Machine Learning with `tidymodels`: Part 3" 
theme: readable
output:
  html_document:
    toc: true
    toc_float: true
    fig_width: 12
    fig_height: 7
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
suppressMessages(suppressWarnings({ 
  library(tidymodels)
  library(here)
  library(palmerpenguins)
  library(tidyverse)
  library(doParallel)
}))
# prefer tidymodels functions in any case of name conflict
tidymodels::tidymodels_prefer() 
```

## What we have covered so far 

Through the first two parts of this workshop we gave an overview of machine learning and the tools to fit machine learning workflows with `tidymodels`. We discussed how machine learning works best when we are interested in *prediction*. We also covered the basics of a machine learning workflow which were:

- How to appropriately spending our data into training and test sets
- Preprocess features when necessary to ensure the best model fit 
- build and fit models 
- Judge model effectiveness using appropriate metrics
- Resampling and cross validation to more effectively train and compare models
- How to tune our models appropriately to increase predictive accuracy

Each one of these steps is common no matter what language or structure you choose to implement your machine learning models. 

In this final part, we will explore some common supervised learning algorithms using `tidymodels`. The goal of this final part is to provide a high level overview of what common algorithms do.  

## Linear Regression

## Regularization and the Lasso

## Classification 

## Random Forests 

## Support Vector Machines

## Ensembles